### PR TITLE
Bump to v0.5.0

### PR DESCRIPTION
**Pull request by vlopes11**

### CODE REVIEW

**Comment by Voxelot** [comment]
yeah this should be a minor bump, as the new features are incompatible and will automatically break any downstream deps.

**Comment by vlopes11** [comment]
@adlerjohn @Voxelot its following the same pattern of https://github.com/FuelLabs/fuel-crypto/pull/19 that, as previously discussed, should also be a minor bump - but we set a patch since no one is using fuel-crypto 0.4

**Comment by adlerjohn** [comment]
Actually, we may have been mistaken on that 😂 https://github.com/FuelLabs/fuels-rs/blame/2b335d7e94ada604075a7495be4280924fc558f2/packages/fuels-signers/Cargo.toml#L15

**Comment by vlopes11** [comment]
> Actually, we may have been mistaken on that joy https://github.com/FuelLabs/fuels-rs/blame/2b335d7e94ada604075a7495be4280924fc558f2/packages/fuels-signers/Cargo.toml#L15

Oh god, fixing haha

**Comment by vlopes11** [comment]
https://github.com/FuelLabs/fuel-crypto/pull/25/commits/640276115fd4f2095bd840497aa63247014bb0bb

**Comment by adlerjohn** [comment]
`:typing_cat:`

**Review by adlerjohn — APPROVED** [review]

**Comment by Voxelot** [comment]
[v0.4.2](https://github.com/FuelLabs/fuel-crypto/releases/tag/v0.4.2) was a fine version bump, there was no breaking changes in that changeset. Adding a new trait impl wont cause any compilation issues downstream, while majorly reworking compiler feature flags would definitely cause some downstream issues without manually adapting.

**Pull request merged**
